version: "{build}"
clone_depth: 5
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
matrix:
  allow_failures:
    - nodejs_version: "4"
    - nodejs_version: "5"
  fast_finish: true
cache:
  - node_modules
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform

  - npm config set spin false
  - npm install -g npm
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
pull_requests:
  do_not_increment_build_number: true
