---
git:
  depth: 1
sudo: false
cache:
  directories:
  - node_modules
language: node_js
matrix:
  allow_failures:
    - node_js: '4'
    - node_js: '5'
  fast_finish: true
  include:
    #
    - node_js: '4'
    - node_js: '5'
    - node_js: '6'
    - node_js: '7'
    - node_js: '8'
    - node_js: node
    #
    - node_js: node
      env: COVERAGE=true
    #
    - node_js: node
      env: TASK=browser BROWSER_NAME=microsoftedge BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=ie BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=chrome BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=firefox BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=ipad BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=iphone BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=safari BROWSER_VERSION="-1..latest"
    - node_js: node
      env: TASK=browser BROWSER_NAME=android BROWSER_VERSION="-1..latest"
before_install:
  - "NPM_VERSION=$(npm --version)"
  - "[ '2.0.0' != `echo -e \"2.0.0\\n$NPM_VERSION\" | sort -Vr | head -n1` ] || npm install -g npm@2"
  - "[ '3.0.0' != `echo -e \"3.0.0\\n$NPM_VERSION\" | sort -Vr | head -n1` ] || npm install -g npm"
  - "npm install -g greenkeeper-lockfile@1"
  - "[ $COVERAGE == false ] || npm install codecov.io"
  - "[ $TASK != browser ] || [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH != master ] || export SAUCE_ACCESS_KEY=$MASTER_SAUCE_ACCESS_KEY"
  - "[ $TASK != browser ] || [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH != master ] || export SAUCE_USERNAME=$MASTER_SAUCE_USERNAME"
before_script:
  - "greenkeeper-lockfile-update"
after_script:
  - "greenkeeper-lockfile-upload"
  - "[ $COVERAGE == false ] || npm run test-cov"
  - "[ $COVERAGE == false ] || cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js && rm -rf ./coverage"
script: "npm run test:$TASK"
env:
  global:
    - COVERAGE=false
    - TASK=node
