---
git:
  depth: 1
sudo: false
cache:
  directories:
  - node_modules
language: node_js
matrix:
  include:
    #
    - node_js: '0.8'
    - node_js: '0.10'
    - node_js: '0.11'
    - node_js: '0.12'
    - node_js: '1'
    - node_js: '2'
    - node_js: '3'
    - node_js: '4'
    - node_js: '5'
    - node_js: node
    #
    - node_js: node
      env: COVERAGE=true
    #
    - node_js: node
      env: TASK=browser BROWSER_NAME=opera BROWSER_VERSION="11..latest"
before_install:
  - "NPM_VERSION=$(npm --version)"
  - "[ '2.0.0' != `echo -e \"2.0.0\\n$NPM_VERSION\" | sort -Vr | head -n1` ] || npm install -g npm@2"
  - "NPM_VERSION=$(npm --version)"
  - "[ '3.0.0' != `echo -e \"3.0.0\\n$NPM_VERSION\" | sort -Vr | head -n1` ] || npm install -g npm"
  - "[ $COVERAGE == false ] || npm install codecov.io"
  - "[ $TASK != browser ] || [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH != master ] || export SAUCE_ACCESS_KEY=$MASTER_SAUCE_ACCESS_KEY"
  - "[ $TASK != browser ] || [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH != master ] || export SAUCE_USERNAME=$MASTER_SAUCE_USERNAME"
after_script:
  - "[ $COVERAGE == false ] || npm run test-cov"
  - "[ $COVERAGE == false ] || cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js && rm -rf ./coverage"
script: "npm run test:$TASK"
env:
  global:
    - COVERAGE=false
    - TASK=node
