---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache:
  directories:
    - $(npm config get cache)
    - $TRAVIS_BUILD_DIR/node_modules

before_cache:
  - rm -vrf $(npm config get cache)/_logs

before_install:
  - "NPM_VERSION=$(npm --version)"
  - "[ '2.0.0' != `echo -e \"2.0.0\\n$NPM_VERSION\" | sort -Vr | head -n1` ] || npm install -g npm@2"
  - "[ '3.0.0' != `echo -e \"3.0.0\\n$NPM_VERSION\" | sort -Vr | head -n1` ] || npm install -g npm"
  - "[ $TASK != browser ] || [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH != master ] || export SAUCE_ACCESS_KEY=$MASTER_SAUCE_ACCESS_KEY"
  - "[ $TASK != browser ] || [ $TRAVIS_PULL_REQUEST != false ] || [ $TRAVIS_BRANCH != master ] || export SAUCE_USERNAME=$MASTER_SAUCE_USERNAME"

before_script:
  - "npx -p greenkeeper-lockfile@1 -c greenkeeper-lockfile-update"
after_script:
  - "npx -p greenkeeper-lockfile@1 -c greenkeeper-lockfile-upload "

script: "npm run test:$TASK"

env:
  global:
    - COVERAGE=false
    - TASK=node

jobs:
  include:

    #

    - stage: Node test
      node_js: node
    -
      node_js: node
      script:
        - npm run test-cov -- --reporter lcovonly
        - npx codecov

    -
      node_js: '4'
    -
      node_js: '5'
    -
      node_js: '6'
    -
      node_js: '7'
    -
      node_js: '8'

    #

    - stage: test on Chrome and Firfox
      env: TASK=browser BROWSER_NAME=chrome BROWSER_VERSION="-1..latest"
    -
      env: TASK=browser BROWSER_NAME=firefox BROWSER_VERSION="-1..latest"

    #

    - stage: test on IE and Edge
      env: TASK=browser BROWSER_NAME=microsoftedge BROWSER_VERSION="-1..latest"
    -
      env: TASK=browser BROWSER_NAME=ie BROWSER_VERSION="-1..latest"

    #

    - stage: test on IPad and IPhone
      env: TASK=browser BROWSER_NAME=ipad BROWSER_VERSION="-1..latest"
    -
      env: TASK=browser BROWSER_NAME=iphone BROWSER_VERSION="-1..latest"

    #

    - stage: test on Safari and Android
      env: TASK=browser BROWSER_NAME=safari BROWSER_VERSION="-1..latest"
    -
      env: TASK=browser BROWSER_NAME=android BROWSER_VERSION="-1..latest"

  fast_finish: true
  allow_failures:
    - node_js: '4'
    - node_js: '5'
